#text sizes
FONT = 'Calibri'
MAIN_TEXT_SIZE = 150
INPUT_FONT_SIZE = 26
SWITCH_FONT_SIZE = 18
BIG_BUTTON_PADDING = 8
SMALL_BUTTON_PADDING = 4
BUTTON_CORNER_RADIUS = 6

#color
GREEN = '#50BFAB'
DARK_GREEN = '#3A8A7B'
WHITE = '#F2F2F2'
BLACK = '#1F1F1F'
LIGHT_GRAY = '#E8E8E8'
GRAY = '#D9D9D9'

#title hex
TITLE_HEX_COLOR = 0x00ABBF50
DWMWA_ATTRIBUTE = 35